-- 修复 schema 与代码不一致的问题

-- 1. cases 表添加缺少的列
ALTER TABLE cases ADD COLUMN source_id VARCHAR(100) NULL;
ALTER TABLE cases ADD COLUMN source_url TEXT NULL;

-- 2. 创建 crawl_templates 表
CREATE TABLE IF NOT EXISTS crawl_templates (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(200) NOT NULL,
  source VARCHAR(50) NOT NULL,
  data_type VARCHAR(50) NOT NULL,
  config JSON NULL,
  description TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- 3. 创建 news 表
CREATE TABLE IF NOT EXISTS news (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(500) NOT NULL,
  content LONGTEXT NULL,
  source VARCHAR(200) NULL,
  url TEXT NULL,
  published_at TIMESTAMP NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- 4. 创建 system_settings 表
CREATE TABLE IF NOT EXISTS system_settings (
  id INT AUTO_INCREMENT PRIMARY KEY,
  `key` VARCHAR(100) NOT NULL UNIQUE,
  value TEXT NULL,
  description VARCHAR(300) NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

SELECT 'Schema fix completed' AS status;
